Update `xchain-ethereum`, `xchain-bitcoin`, `xchain-binance`
xchainjs/xchainjs-lib pull request #159
Opened 2020-12-29 13:25 UTC by junkai121

Update comments for xchain-ethereum, xchain-bitcoin, xchain-binance.

2020-12-29 18:02 UTC, veado requested changes
Very detailed work :+1: _Just few (small) change requests ..._

2020-12-29 18:02 UTC, veado commented on packages/xchain-ethereum/src/utils.ts
> -     */
Let's keep this helpful comment, but comment it using `// ...` if we do need to avoid it to get generated as documentation.

2020-12-29 18:02 UTC, veado commented on packages/xchain-ethereum/src/utils.ts
> -     */
Let's keep this helpful comment

2020-12-30 02:27 UTC, junkai121 commented on packages/xchain-ethereum/src/client.ts
> +   * @template T The result interface.
https://tsdoc.org/pages/tags/typeparam/
@veado, you can check @template ^.

2020-12-30 11:58 UTC, veado approved these changes

2020-12-30 12:10 UTC, merged