Return 0 balances everywhere
xchainjs/xchainjs-lib pull request #367
Opened 2021-06-25 14:18 UTC by severinwullschleger

getBalance should always return an array at least containing the mainAsset of a chain.

ETH, BTC; BCH and LTC are already behaving like that. 

I added the same behaviour to RUNE and BNB

2021-06-28 08:38 UTC, veado requested changes
@severinwullschleger LGTM, just few (small) suggestions ...

2021-06-28 08:38 UTC, veado commented on packages/xchain-thorchain/src/client.ts
> +            amount: baseAmount('0.0', DECIMAL),
[nitpick] `baseAmount(0, DECIMAL)`

2021-06-28 08:38 UTC, veado commented on packages/xchain-cosmos/src/client.ts
> +            amount: baseAmount('0.0', DECIMAL),
[nitpick] `baseAmount(0, DECIMAL)`

2021-06-28 08:38 UTC, veado commented on packages/xchain-cosmos/__tests__/client.test.ts
> +    expect(balances[0].asset).toEqual(AssetAtom)
To be safe: 
```ts
expect(assetToString(balances[0].asset)).toEqual(assetToString(AssetAtom))
```

2021-06-28 08:38 UTC, veado commented on packages/xchain-thorchain/__tests__/client.test.ts
> +    expect(balances[0].asset).toEqual(AssetRune)
To be safe: 
```ts
expect(assetToString(balances[0].asset)).toEqual(assetToString(AssetRune))
```

2021-06-28 08:38 UTC, veado commented on packages/xchain-binance/src/client.ts
> +            amount: assetToBase(assetAmount('0.0', 8)),
Could you add `const BNB_DECIMAL = 8` to 'xchainjs-lib/packages/xchain-binance/src/utils.ts` (similar to other packages) to use it for example as follow here ^:

`assetToBase(assetAmount('0.0', 8))` -> `baseAmount(0, BNB_DECIMAL)`

2021-06-28 08:38 UTC, veado commented on packages/xchain-binance/__tests__/client.test.ts
> +    expect(balances[0].asset.ticker === 'BNB').toBeTruthy()
Same here?
```ts
expect(assetToString(balances[0].asset)).toEqual(assetToString(AssetBNB))
```

2021-06-28 08:38 UTC, veado commented on packages/xchain-binance/__tests__/client.test.ts
> +    expect(balances[0].asset.ticker === 'BNB').toBeTruthy()
Maybe this?
```ts
expect(assetToString(balances[0].asset)).toEqual(assetToString(AssetBNB))
```

2021-06-28 16:33 UTC, veado submitted a review, later dismissed

2021-06-28 16:35 UTC, veado commented
@severinwullschleger Last change request: Pls bump versions in `package.json` of each `xchain-*` packages you have updated and add a note in CHANGELOG? After bumping + merging your updates can be published to npm then. Thx!

2021-06-30 10:22 UTC, severinwullschleger commented
@veado did that

2021-07-26 09:50 UTC, severinwullschleger commented
@veado fixed the conflicts, can you merge it?

2022-03-31 09:22 UTC, matikucharski commented
Is it going to be merged?

2022-04-04 06:46 UTC, veado commented
> Is it going to be merged?

Conflicts need to be fixed before going to merge, anyone?

2023-09-04 01:52 UTC, closed without merging