added index for sender
xchainjs/xchainjs-lib pull request #375
Opened 2021-07-01 19:23 UTC by maikelmclauflin

subtle bug for sender address derivation

2021-07-02 21:21 UTC, reidrankin commented
(I've picked up this fix in #376)

2021-07-07 08:48 UTC, davidp94 approved these changes

2021-07-07 12:58 UTC, veado reviewed
Not sure if I miss something, but it seems this PR just added a `try/catch` block, we don't want anymore. Changes of 57de816fc82e54cb82988a03258466f4af7d3cfb seems to be already in `master`. In this case, let's close this PR.

2021-07-07 13:01 UTC, veado requested changes
https://github.com/xchainjs/xchainjs-lib/pull/375#pullrequestreview-700972457

2021-07-07 13:15 UTC, davidp94 commented
> [#375 (review)](https://github.com/xchainjs/xchainjs-lib/pull/375#pullrequestreview-700972457)

I don't see it there https://github.com/xchainjs/xchainjs-lib/blob/master/packages/xchain-bitcoincash/src/client.ts#L347

2021-07-07 13:21 UTC, davidp94 commented
I will remove the try catch block

2021-07-07 13:39 UTC, reidrankin reviewed
I'll merge this this morning after I get #386 in.

2021-07-07 13:39 UTC, reidrankin commented on packages/xchain-bitcoincash/src/client.ts
> +    return broadcastTx({
They're functionally equivalent, but `return await` gives nicer stack traces.

2021-07-07 13:43 UTC, davidp94 commented
Thanks.

Le mer. 7 juil. 2021 à 13:39, Reid Rankin ***@***.***> a
écrit :

> ***@***.**** commented on this pull request.
>
> I'll merge this this morning after I get #386
> <https://github.com/xchainjs/xchainjs-lib/pull/386> in.
> ------------------------------
>
> In packages/xchain-bitcoincash/src/client.ts
> <https://github.com/xchainjs/xchainjs-lib/pull/375#discussion_r665379059>:
>
> > @@ -358,7 +358,7 @@ class Client extends BaseXChainClient implements BitcoinCashClient, XChainClient
>      const tx = builder.build()
>      const txHex = tx.toHex()
>
> -    return await broadcastTx({
> +    return broadcastTx({
>
> They're functionally equivalent, but return await gives nicer stack
> traces.
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub
> <https://github.com/xchainjs/xchainjs-lib/pull/375#pullrequestreview-701017201>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AGFVWNNBM3WHB5YLRCXOUNLTWRKJLANCNFSM47VKMZNQ>
> .
>

2021-07-07 14:06 UTC, reidrankin commented on packages/xchain-bitcoincash/src/client.ts
> +    return broadcastTx({
```suggestion
    return await broadcastTx({
```

2021-07-07 14:35 UTC, veado approved these changes

2021-07-07 14:53 UTC, reidrankin approved these changes
rebased and squashed

2021-07-07 14:53 UTC, merged