add xchain-terra
xchainjs/xchainjs-lib pull request #462
Opened 2022-01-09 00:57 UTC by mikewyszinski

2022-02-02 18:02 UTC, veado requested changes
Nice job! Just few change requests ... 

Pls merge latest master again.

2022-02-02 22:24 UTC, mikewyszinski commented on packages/xchain-terra/src/client.ts
> +const DECIMALS = 6
yes -> https://pkg.go.dev/github.com/terra-money/core@v0.5.14/types/assets#pkg-types

2022-02-03 19:12 UTC, mikewyszinski commented on packages/xchain-terra/src/client.ts
> +      throw new Error('Only LUNA or UST transfers are currently supported on terra')
yeah wasn't sure about this, glad you brought it up, i believe TC will only have UST/LUNA pools to start, but i'm going to remove those check and support all native terra xfers

2022-02-04 05:19 UTC, mikewyszinski commented on packages/xchain-terra/src/client.ts
> +    // console.log(send.toJSON())
done

2022-02-04 05:21 UTC, mikewyszinski commented on packages/xchain-terra/__tests__/client.test.ts
> +// }
i left this commented code because i need to add unit tests for other methods....still a WIP

2022-02-04 13:51 UTC, merged