getChainId from thornode before posting to deposit handler
xchainjs/xchainjs-lib pull request #463
Opened 2022-01-10 20:08 UTC by pluto-9r

- use cosmos node info to get network so that chain ID can be set

2022-01-10 20:13 UTC, thorswapdev approved these changes
LGTM!

2022-01-11 08:40 UTC, veado requested changes
Code looks ok. Pls check tests - they are still failing. Update CHANGELOG + bump version no. if you plan to release a next version.

2022-01-11 15:54 UTC, pluto-9r commented
@veado tests fixed as of https://github.com/xchainjs/xchainjs-lib/pull/463/commits/ecfcd0de434b351c2cd52ad32a90f625a945fc13.

changelog and version bumped as of https://github.com/xchainjs/xchainjs-lib/pull/463/commits/6fde01de13dc0d10d4f66e1e0adee647714dc279

2022-01-11 16:03 UTC, veado approved these changes

2022-01-11 16:03 UTC, merged