Chain and asset agnostic refactor
xchainjs/xchainjs-lib pull request #705
Opened 2022-12-22 19:04 UTC by ahdzib-maya

- Changed `Chain` to less strict `string` type.
- Moved all chain definitions to each package's `utils.ts`.
- Duplicated all asset definitions to each package's `utils.ts`.
- Removed `chain.ts` and all of its functions.
- Moved `isAssetNativeRune` to `xchain-thorchain`.
- Moved all imports from `xchain-util` to `xchain-*` regarding asset and chains.

Implicit suggestions with the changes:
- Avoid importing both *Asset** and **Chain*, use `Asset*.chain` if imported.
- Leave chain names with shorthand style (e.g. `BTCChain` instead of `BitcoinChain`)
- Have *Asset** and **Chain* definitions in `utils.ts` instead of `const.ts`. (Made more sense for me)
- Standardize `utils.ts` in all packages.

2022-12-23 06:03 UTC, veado requested changes
Looks good, some minor changes:
-Keep constants in `const.ts` everywhere
- Use `{XYZ}Chain` instead of `{XYZAsset.chain}` everywhere

2022-12-23 06:03 UTC, veado commented on packages/xchain-util/src/asset.ts
> +export const AssetBCH: Asset = { chain: 'BCH', symbol: 'BCH', ticker: 'BCH', synth: false }
Remove all `const Asset{XYZ}` from `asset.ts`. If you do need these in tests, define it there, but don`t export. _I've read your message about at Discord..._

2022-12-24 09:10 UTC, veado requested changes
Two last things:
-  `AssetAtom.chain` -> `GaiaChain` everywhere
- Pls bump packages + update CHANGELOG's

   - `xchain-util`: Bump `minor` version (breaking change)
   - other packages: Bump `patch` version + update its deps to latest `xchain-util`
   
   @mikewyszinski If you have a chance, pls review.

2022-12-26 05:40 UTC, veado approved these changes
:+1:

2022-12-27 18:14 UTC, veado requested changes
Last change request (just realized):
- Use latest `"xchain-util@0.12.0"` in `xchain-client`
- Bump `xchain-client` to `0.13.5`
- Use `xchain-client@0.13.5` in other packages

2022-12-28 01:04 UTC, mikewyszinski approved these changes

2022-12-28 07:40 UTC, veado approved these changes

2022-12-28 07:40 UTC, merged