Fix derive path for xchain-bitcoin
xchainjs/xchainjs-lib pull request #92
Opened 2020-11-10 02:45 UTC by junkai121

2020-11-10 08:08 UTC, veado requested changes
LGTM. Just few suggestions.

2020-11-10 08:08 UTC, veado commented on packages/xchain-bitcoin/src/client.ts
> +
Let keep it private: `private derive_path = {...}` or define `export const DERIVE_PATH = `{...}` outside from `Client`

2020-11-10 08:08 UTC, veado commented on packages/xchain-bitcoin/src/client.ts
> +    const network = isTestnet ? Bitcoin.networks.testnet : Bitcoin.networks.bitcoin
Since we do same thing in other methods, how about to extract it into `btcNetwork = (): Network => {...}`?

Same for `isTestnet`.

2020-11-10 08:08 UTC, veado commented on packages/xchain-bitcoin/src/client.ts
> +    const derive_path = isTestnet ? this.derive_path.testnet : this.derive_path.mainnet
How about to provide a `derivePath` method? If we make `derive_path` private, the users can still ask for the path.

2020-11-10 11:24 UTC, veado approved these changes
P.S. Pls don't merge before tests have been fixed.

2020-11-11 04:28 UTC, HelloKashif commented
The failing tests have been fixed in this PR: https://github.com/xchainjs/xchainjs-lib/pull/98

Pr-98 already contains this PR's stuff so we can close this one and just merge 98

2020-11-11 04:43 UTC, merged